#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 24 13:06:40 2019

@author: nokicheng
"""

import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt

#function that returns dy/dt
def model(y,t,k):
    return -k*y

#initial condition
y0 = 5
k = 0.3

#time points
t = np.linspace(0,20,50)

#solve ODE
y = odeint(model,y0,t,args=(k,))

#plot results
plt.plot(t,y)
plt.xlabel('time')
plt.ylabel('y(t)')
plt.show()